import { imgs } from './imgs';
import { logos } from './logos';

const { css_logo, html_logo, react_logo, psql_logo, js_logo, node_logo } = logos;

export const projectInfo = [
    {
        title: 'Background Generator',
        image: imgs[0],
        description: `Background Generator generates a linear gradient background with 2 custom colors and 4 directions chosen by the user. I've personally used this to create Robofriends and SmartBrain's background.`,
        stack: 'HTML, CSS, JavaScript',
        source: 'https://github.com/hsKim93/Background-Generator',
        web: 'https://hskim93.github.io/Background-Generator/',
        stacks: [html_logo, css_logo, js_logo]
    },
    {
        title: 'Movie App',
        image: imgs[1],
        description: 'Movie-App is a showcase of 20 movies generated by a proxy API provided by an online tutor.',
        stack: 'HTML, CSS, React.js',
        source: 'https://github.com/hsKim93/Movie-App',
        web: 'https://hskim93.github.io/Movie-App/',
        stacks: [html_logo, css_logo, react_logo]

    },
    {
        title: 'Robofriends',
        image: imgs[2],
        description: 'Robofriends is a website that allows users to search robots generated by using JSONPlaceholder API and ROBOHASH API.',
        stack: 'HTML, CSS, React.js',
        source: 'https://github.com/hsKim93/robofriends',
        web: 'https://hskim93.github.io/robofriends/',
        stacks: [html_logo, css_logo, react_logo]

    }, 
    {
        title: 'SmartBrain',
        image: imgs[3],
        description: 'SmartBrain is a face detection app that uses a well-trained AI from the Clarifai API. ' +
        'It has a full register, login functionality, as well as its own server made with nodejs and a database made with PostgresSQL where it stores users hashed credentials ' +
        'using bcrypt-nodejs.',
        stack: 'HTML, CSS, React.js, node.js ',
        source: 'https://github.com/hsKim93/SmartBrain',
        web: 'https://hskim93.github.io/SmartBrain/',
        stacks: [html_logo, css_logo, react_logo, node_logo, psql_logo]

    }
]